import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../../styles/global.css'
import Provider from 'ui/components/AuthProvider'
import React from 'react'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}): React.ReactNode {
    // const session = await getServerSession(authOptions)
    return (
        <html lang="en">
            <body className={inter.className}>
                {/*<TopBar/>*/}
                <Provider>{children}</Provider>
            </body>
        </html>
    )
}
