import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) : JSX.Element{
  return (
    <html lang="en">
          <body className={inter.className}>
      {/*<TopBar/>*/}
      <section className="bg-black text-emerald-600 w-max">
dasdasd
      {children}
      </section>

      </body>
    </html>
  )
}
